--CREATING A TABLE
CREATE TABLE my_employee
(
    ID NUMBER(4) PRIMARY KEY NOT NULL,
    LAST_NAME VARCHAR (25),
    FIRST_NAME VARCHAR (25) NOT NULL,
    USER_ID VARCHAR (25) UNIQUE,
    SALARY NUMBER (9,2)
    -- PRIMARY KEY(ID),
    -- NOT NULL (ID)
);

--INSERTING INTO THE TABLE
INSERT INTO my_employee VALUES(1,'LUFFY', 'MONKEY D.', 11, 1000);
INSERT INTO my_employee VALUES(2,'ZORO', 'RORONOA ', 12, 1100);
INSERT INTO my_employee VALUES(3,'GARP', 'MONKEY D.', 13, 1200);
INSERT INTO my_employee VALUES(4,'DRAGON', 'MONKEY D.', 14, 1300);

--CONFORMING THE ADDITION TO THE TABLE
DESCRIBE my_employee;

--MAKE DATA ADDITION PERMANENT
COMMIT;

--CHANGING DATA
UPDATE my_employee
SET LAST_NAME = 'MIHAWK'
WHERE ID = 2;

UPDATE my_employee
SET SALARY = 1200
WHERE SALARY < 1200;

--DELETING FROM TABLE
DELETE FROM my_employee
WHERE LAST_NAME = 'ZORO' AND FIRST_NAME= 'RORONOA';

COMMIT;

DESCRIBE my_employee;

SELECT * FROM my_employee;